routes/web.php
<?php

use Illuminate\Support\Facades\Redirect;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
// Route::get('/home', function () {

// });
Route::get('/', 'StopController@index')->name('logged_out_home');
// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/home', 'StopController@index')->name('logged_in_home');
// Route::group(['middleware' => 'auth'], function () {
//     Route::post('stops', 'StopController@web_post')->name('stops_post');
// });
// stops
Route::resource(
    'stops',
    'StopController',
    ['only' => ['index', 'create', 'store', 'destroy', 'edit', 'update']]
);
Route::any('/stops/search', 'StopController@search')->name('stops.search');

Route::get('/stops/{id}/updatetask', 'StopController@update_task')->name('stops.updatetask');
Route::post('/stops/task/store', 'StopController@store_task')->name('stop.store.task');
//Route::get('posts/{post}/comments/{comment}', function ($postId, $commentId) {
//
//});
// Route::get('/stops', 'StopController@web_index')->name('stops');
// Route::get('/stops/create', 'StopController@web_create')->name('create_stop');
// Route::post('/stops/store', 'StopController@web_store')->name('store_stop');
// tasks
Route::resource(
    'tasks',
    'TaskController',
    ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]
);
// Route::get('/tasks', 'TaskController@web_index')->name('tasks.index');
// Route::get('/tasks/create', 'TaskController@web_create')->name('tasks.create');
// Route::post('/tasks/store', 'TaskController@web_store')->name('tasks.store');
// Route::delete('/tasks/destroy/{id}', 'TaskController@destroy')->name('tasks.destroy');
// rewards
Route::resource(
    'rewards',
    'RewardController',
    ['only' => ['index', 'create', 'store', 'destroy']]
);

app/Stop.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Stop extends Model
{
    public function Town()
    {
        return $this->hasOne('App\Town', 'id', 'towns_id');
    }
    public function Task()
    {
        return $this->hasOne('App\Task', 'id', 'tasks_id');
    }
    public function Reward()
    {
        return $this->hasOne('App\Reward', 'id', 'rewards_id');
    }
}

app/Http/Controllers/StopController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use App\Http\Requests;
use App\Stop;
use App\Town;
use App\Task;
use App\Reward;
use App\Http\Resources\Stop as StopResource;
use View;
use function GuzzleHttp\Promise\all;

class StopController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function index()
    // {

    //     // Get stops
    //     $stops = Stop::with('Town')->with('Task')->with('Reward')->paginate(15);
    //     // Return collection of stops as a resource
    //     return StopResource::collection($stops);

    // }
    public function index()
    {

        $stops = Stop::orderBy('name')->with('Town')->with('Task')->with('Reward')->paginate(6);
        return View::make('stops.stops', compact('stops'));
    }
    public function search()
    {
        $q = Input::get('q');

        $stops = Stop::where('name', 'LIKE', '%' . $q . '%')->orderBy('name')->with('Town')->with('Task')->with('Reward')->paginate(6)->setPath('');

        $pagination = $stops->appends(array(
            'q' => Input::get('q')
        ));
        return View::make('stops.stops', compact('stops', 'pagination', 'q'));
    }
    public function update_task($id)
    {
        $stop = Stop::with('Task')->with('Reward')->find($id);
        $tasks = Task::all();
        $rewards = Reward::all();

        // return $stop ;
        return View::make('stops.task', compact('stop', 'rewards', 'tasks'));
    }
    public function create()
    {
        if (\Auth::user()->group != 42) {
            return redirect('home');
        }
        $towns = Town::all();
        $stop = new Stop();
        return View::make('stops.create', compact('stop', 'towns'));
    }
    public function edit($id)
    {
        if (\Auth::user()->group != 42) {
            return redirect('home');
        }
        $towns = Town::all();
        $stop = Stop::find($id);
        return View::make('stops.edit', compact('stop', 'towns'));
    }
    public function add_task_reward($id)
    {
        $stop = Stop::find($id);
        dd($stop);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    // public function store(Request $request)
    // {
    //     if (\Auth::user()->group != 42) {
    //         return redirect('home');
    //     }
    //     $stop = $request->isMethod('put') ? Stop::findOrFail($request->stop_id) : new Stop;
    //     $stop->id = $request->input('stop_id');
    //     $stop->name = $request->input('name');
    //     $stop->gym = $request->input('gym') ? $request->input('gym') : 0;
    //     $stop->towns_id = $request->input('towns_id');
    //     $stop->tasks_id = $request->input('tasks_id') ? $request->input('tasks_id') : 0;
    //     $stop->rewards_id = $request->input('rewards_id') ? $request->input('rewards_id') : 0;
    //     $stop->gps = '';
    //     $stop->img = '';
    //     $stop->status = $request->input('status') ? $request->input('status') : 'requested';
    //     if ($stop->save()) {
    //         return new StopResource($stop);
    //     }
    // }
    public function store(Request $request)
    {
        if (\Auth::user()->group != 42) {
            return redirect('home');
        }
        die('store');
        $stop = $request->isMethod('put') ? Stop::findOrFail($request->stop_id) : new Stop;
        $stop->id = $request->input('stop_id');
        $stop->name = $request->input('name');
        $stop->gym = $request->input('gym') ? $request->input('gym') : 0;
        $stop->towns_id = $request->input('towns_id');
        $stop->tasks_id = $request->input('tasks_id') ? $request->input('tasks_id') : 0;
        $stop->rewards_id = $request->input('rewards_id') ? $request->input('rewards_id') : 0;
        $stop->gps = $request->input('gps') ? $request->input('gps') : '';
        $stop->img = '';
        $stop->status = $request->input('status') ? $request->input('status') : 'requested';
        if ($stop->save()) {
            return redirect('stops');
        }
    }
    public function update(Request $request, $id)
    {
        if (\Auth::user()->group != 42 && !Stop::findOrFail($id)) {
            return redirect('home');
        }

        $stop = Stop::findOrFail($id);
        $stop->name = $request->input('name');
        $stop->gym = $request->input('gym') ? $request->input('gym') : 0;
        $stop->towns_id = $request->input('towns_id');
        $stop->tasks_id = $request->input('tasks_id') ? $request->input('tasks_id') : 0;
        $stop->rewards_id = $request->input('rewards_id') ? $request->input('rewards_id') : 0;
        $stop->gps = $request->input('gps') ? $request->input('gps') : '';
        $stop->img = '';
        $stop->status = $request->input('status') ? $request->input('status') : 'requested';
        if ($stop->save()) {
            return redirect('stops');
        }
    }
    public function store_task(Request $request)
    {

        $stop = Stop::findOrFail($request->stop_id);
        $stop->tasks_id = $request->input('tasks_id') ? $request->input('tasks_id') : 0;
        $stop->rewards_id = $request->input('rewards_id') ? $request->input('rewards_id') : 0;

        if ($stop->save()) {
            return redirect('stops');
        } else {
            return redirect('stops');
        }
    }

    // public function show($id)
    // {
    //     // Get stop
    //     $stop = Stop::findOrFail($id);
    //     // Return single stop as a resource
    //     return new StopResource($stop);
    // }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (\Auth::user()->group != 42) {
            return redirect('home');
        }
        // Get stop
        $stop = Stop::findOrFail($id);
        if ($stop->delete()) {
            return redirect('stops');
        }
    }
}

resources/views/stops/create.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Stop</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('stops.store') }}"
                        aria-label="Create Stop">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label
                                text-md-right">Stop name</label>

                            <div class="col-md-6">
                                <input id="name" type="text"
                                    class="form-control{{ $errors->has('name') ?
                                ' is-invalid' : '' }}" name="name"
                                value="{{$stop->name }}" required autofocus>

                                @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @endif
                            </div>
                            <br>
                            <label for="name" class="col-md-12 col-form-label
                                text-md-left">Stop gps format:
                                52.87090420558121&6.001826226711273</label>
                            <b for="name" class="col-md-12 col-form-label
                                text-md-left">Stop gps gen :
                                <a href="https://www.openstreetmap.org">https://www.openstreetmap.org</a></label>
                            <div class="col-md-12">
                                <input id="gps" type="text"
                                    class="form-control" name="gps"
                                    value="{{$stop->gps }}" autofocus>


                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="town">Town</label>
                            <select class="form-control" id="town"
                                name="towns_id">
                                @foreach($towns as $town)
                                <option value="{{$town->id}}">{{$town->name}}</option>
                                @endforeach

                            </select>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/stops/edit.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Update Stop</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('stops.update', $stop->id)
                        }}"
                        aria-label="Update Stop">
                        @method('PATCH')
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label
                                text-md-right">Stop name</label>

                            <div class="col-md-6">
                                <input id="name" type="text"
                                    class="form-control{{ $errors->has('name') ?
                                ' is-invalid' : '' }}" name="name"
                                value="{{$stop->name }}" required autofocus>

                                @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @endif
                            </div>
                            <br>
                            <label for="name" class="col-md-12 col-form-label
                                text-md-left">Stop gps format:
                                52.87090420558121&6.001826226711273</label>
                            <b for="name" class="col-md-12 col-form-label
                                text-md-left">Stop gps gen :
                                <a href="https://www.openstreetmap.org">https://www.openstreetmap.org</a></label>
                            <div class="col-md-12">
                                <input id="gps" type="text"
                                    class="form-control" name="gps"
                                    value="{{$stop->gps }}" autofocus>


                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="town">Town</label>
                            <select class="form-control" id="town"
                                name="towns_id">
                                @foreach($towns as $town)
                                <option value="{{$town->id}}">{{$town->name}}</option>
                                @endforeach

                            </select>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/stops/stop.blade.php
@extends('layouts.main')
@section('content')
    i am the details    
@stop

resources/views/stops/stops.blade.php
@extends('layouts.main')
@section('content')
<div class="row title">
    <h1>Poke stops</h1>
</div>
<!-- <div class="row searchbar" style="padding:15px;">
    <div class="col-md-3">
        <div class="form-group">
            <label for="town">Town</label>
            <select class="form-control" id="town">
                <option>Wolvega</option>
                <option>Heerenveen</option>
                <option>De Blesse</option>
            </select>
        </div>
    </div>

    <div class="col-md-3">
        <div class="form-group">
            <label for="mission">Mission</label>
            <select class="form-control" id="mission">
                <option>Catch 3</option>
                <option>Catch 4</option>
                <option>Catch 5</option>
            </select>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <label for="reward">Reward</label>
            <select class="form-control" id="reward">
                <option>Cubone</option>
                <option>Ghastly</option>
                <option>Mewto</option>
            </select>
        </div>
    </div>
</div> -->
<!-- <div class="row filters-on">
    <div class="col-md-12">
        <span class="badge badge-primary">Cubone</span>
        <span class="badge badge-primary">Wolvega</span>
    </div>
</div>
<hr> -->
<div class="row">
    @guest
    @else
    <div class="col-lg-1">
        @if(\Auth::user()->group == 42)
        <a href="{{ route('stops.create') }}" class="btn btn-primary">
            Add
        </a>
        @endif
    </div>
    @endguest
</div>
@if(isset($stops))
<br>
<div class="row">

    <div class="container">
        <form action="{{ route('stops.search') }}" method="POST" role="search">
            {{ csrf_field() }}
            <div class="input-group">
                <input type="text" class="form-control" name="q"
                    placeholder="Search stops" value="<?=isset($q)?$q:''?>">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default">
                        <i class="fa
                            fa-search bigfonts" aria-hidden="true"></i>
                    </button>
                </span>
            </div>
        </form>
    </div>
</div>
<br>
<div class="row">

    <div class="col-12">
        {!! $stops->render() !!}
    </div>
</div>
<div class="row">

    @foreach ( $stops as $stop)

    <div id="content" class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-4">
        @include('partial.stop_card',
        [$title=$stop->name,
        $id=$stop->id,
        $town=$stop->Town->name,
        $task=$stop->Task!=null?$stop->Task->description:'none',
        $stopUpdatedTime=$stop->updated_at,
        $stopUpdatedToday=$stop->updated_at->isToday(),
        $gps=$stop->gps,
        $reward=$stop->Reward!=null?$stop->Reward->description:'none',
        ])
        @guest
        @else
        @if(\Auth::user()->group == 42)
        <div class="row">
            <div class="col-6">
                <a href="{{ route('stops.edit',$stop->id)}}" class="btn
                    btn-primary">Edit</a>
            </div>
            <div class="col-6">
                <form action="{{ route('stops.destroy',[$stop->id])}}"
                    method="post" style="float:right;">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </div>
        </div>


        @endif
        @endguest
    </div>
    @endforeach

</div>
<br>
<div class="row">

    <div class="col-12">
        {!! $stops->render() !!}
    </div>
</div>
@endif
@stop

resources/views/stops/task.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Stop</div>

                <div class="card-body">
                    <form method="POST" action="{{
                        route('stop.store.task') }}"
                        aria-label="Set stop task">
                        @csrf
                        <input type="hidden" name="stop_id" value="{{$stop->id}}">
                        <div class="form-group row">
                            <label for="task">Task</label>
                            <select class="form-control" id="task"
                                name="tasks_id">
                                @foreach($tasks as $task)
                                <option value="{{$task->id}}">{{$task->description}}</option>
                                @endforeach

                            </select>
                        </div>
                        <div class="form-group row">
                            <label for="reward">Reward</label>
                            <select class="form-control" id="reward"
                                name="rewards_id">
                                @foreach($rewards as $reward)
                                <option value="{{$reward->id}}">{{$reward->description}}</option>
                                @endforeach

                            </select>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop