routes/web.php
<?php

use Illuminate\Support\Facades\Redirect;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
// Route::get('/home', function () {

// });
Route::get('/', 'StopController@index')->name('logged_out_home');
// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/home', 'StopController@index')->name('logged_in_home');
// Route::group(['middleware' => 'auth'], function () {
//     Route::post('stops', 'StopController@web_post')->name('stops_post');
// });
// stops
Route::resource(
    'stops',
    'StopController',
    ['only' => ['index', 'create', 'store', 'destroy', 'edit', 'update']]
);
Route::any('/stops/search', 'StopController@search')->name('stops.search');

Route::get('/stops/{id}/updatetask', 'StopController@update_task')->name('stops.updatetask');
Route::post('/stops/task/store', 'StopController@store_task')->name('stop.store.task');
//Route::get('posts/{post}/comments/{comment}', function ($postId, $commentId) {
//
//});
// Route::get('/stops', 'StopController@web_index')->name('stops');
// Route::get('/stops/create', 'StopController@web_create')->name('create_stop');
// Route::post('/stops/store', 'StopController@web_store')->name('store_stop');
// tasks
Route::resource(
    'tasks',
    'TaskController',
    ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]
);
// Route::get('/tasks', 'TaskController@web_index')->name('tasks.index');
// Route::get('/tasks/create', 'TaskController@web_create')->name('tasks.create');
// Route::post('/tasks/store', 'TaskController@web_store')->name('tasks.store');
// Route::delete('/tasks/destroy/{id}', 'TaskController@destroy')->name('tasks.destroy');
// rewards
Route::resource(
    'rewards',
    'RewardController',
    ['only' => ['index', 'create', 'store', 'destroy']]
);

resources/views/includes/footer.blade.php
<div id="copyright text-right">© Copyright 2019 pokeapp</div>

resources/views/includes/head.blade.php
<meta charset="utf-8">
<meta name="description" content="poke stops and raids">
<meta name="author" content="Kenny de Jong">

<title>Pokeapp</title>

<!-- load bootstrap from a cdn must be local at some time-->

<link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
<link rel="stylesheet"
    href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css"
    />
<link href="{{ asset('/font-awesome/css/font-awesome.min.css') }}"
    rel="stylesheet"
    type="text/css" />
<link rel="stylesheet" href="{{ asset('/css/main.css') }}">

resources/views/includes/header.blade.php
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Pokeapp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {{ request()->is('home') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('logged_in_home') }}">Home
                    <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {{ request()->is('stops*') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('stops.index') }}">Stops</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Gyms</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Raid Groups</a>
            </li>
            @auth
            <li class="nav-item {{ request()->is('tasks*') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('tasks.index') }}">Tasks</a>
            </li>
            <li class="nav-item {{ request()->is('rewards*') ? 'active' : ''
                }}">
                <a class="nav-link" href="{{ route('rewards.index') }}">Rewards</a>
            </li>
            @endauth
        </ul>

        @if (Route::has('login'))
        <ul class="nav navbar-nav pull-right">
            @auth
            <li class="nav-item">
                <a class="nav-link" href="{{
                    route('logout') }}"
                    onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{
                    route('logout') }}" method="POST"
                    style="display: none;">
                    @csrf
                </form>
            </li>
            @else
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">Login</a>
            </li>

            @if (Route::has('register'))
            <li class="nav-item">
                <a class="nav-link" href="{{ route('register') }}">Register</a>
            </li>
            @endif
            @endauth
        </ul>
        @endif
        {{-- <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search"
                aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> --}}
    </div>
</nav>

resources/views/includes/sidebar.blade.php
<!-- sidebar nav -->
    <nav id="sidebar-nav">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="#">a</a></li>
            <li><a href="#">b</a></li>
            <li><a href="#">c</a></li>
        </ul>
    </nav>