routes/web.php
<?php

use Illuminate\Support\Facades\Redirect;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
// Route::get('/home', function () {

// });
Route::get('/', 'StopController@index')->name('logged_out_home');
// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/home', 'StopController@index')->name('logged_in_home');
// Route::group(['middleware' => 'auth'], function () {
//     Route::post('stops', 'StopController@web_post')->name('stops_post');
// });
// stops
Route::resource(
    'stops',
    'StopController',
    ['only' => ['index', 'create', 'store', 'destroy', 'edit', 'update']]
);
Route::any('/stops/search', 'StopController@search')->name('stops.search');

Route::get('/stops/{id}/updatetask', 'StopController@update_task')->name('stops.updatetask');
Route::post('/stops/task/store', 'StopController@store_task')->name('stop.store.task');
//Route::get('posts/{post}/comments/{comment}', function ($postId, $commentId) {
//
//});
// Route::get('/stops', 'StopController@web_index')->name('stops');
// Route::get('/stops/create', 'StopController@web_create')->name('create_stop');
// Route::post('/stops/store', 'StopController@web_store')->name('store_stop');
// tasks
Route::resource(
    'tasks',
    'TaskController',
    ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]
);
// Route::get('/tasks', 'TaskController@web_index')->name('tasks.index');
// Route::get('/tasks/create', 'TaskController@web_create')->name('tasks.create');
// Route::post('/tasks/store', 'TaskController@web_store')->name('tasks.store');
// Route::delete('/tasks/destroy/{id}', 'TaskController@destroy')->name('tasks.destroy');
// rewards
Route::resource(
    'rewards',
    'RewardController',
    ['only' => ['index', 'create', 'store', 'destroy']]
);

app/Reward.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reward extends Model
{
    //
}

app/Http/Controllers/RewardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Reward;
use View;
use App\Http\Resources\Reward as RewardResource;
use function GuzzleHttp\Promise\all;

class RewardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Get rewards
        $rewards = Reward::all();
        // Return collection of rewards as a resource
        return View::make('rewards.rewards', compact('rewards'));
    }

    public function create()
    {
        if (\Auth::user()->group != 42) {
            return redirect('home');
        }
        $rewards = Reward::all();
        return View::make('rewards.create', compact('rewards'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (\Auth::user()->group != 42) {
            return redirect('home');
        }
        $reward = $request->isMethod('put') ? Reward::findOrFail($request->reward_id) : new Reward;
        $reward->id = $request->input('reward_id');
        $reward->title = $request->input('title');
        $reward->description = $request->input('description');
        $reward->active = $request->input('active') ? $request->input('active') : 0;
        $reward->status = $request->input('status') ? $request->input('status') : 'requested';
        if ($reward->save()) {
            return redirect('rewards');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function show($id)
    // {
    //     // Get reward
    //     $reward = Reward::findOrFail($id);
    //     // Return single reward as a resource
    //     return new RewardResource($reward);
    // }

    public function destroy($id)
    {
        // Get reward
        $reward = Reward::findOrFail($id);
        if ($reward->delete()) {
            return redirect('rewards');
        }
    }
}

resources/views/rewards/create.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Reward</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('rewards.store') }}"
                        aria-label="Create Stop">
                        @csrf

                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label
                                text-md-right">reward title (type of reward)</label>
                            <div class="col-md-6">
                                <input id="title" type="text"
                                    class="form-control{{ $errors->has('title')
                                ?
                                ' is-invalid' : '' }}" name="title" value="{{
                                old('title') }}" required autofocus>

                                @if ($errors->has('title'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="description" class="col-md-4
                                col-form-label
                                text-md-right">reward description</label>

                            <div class="col-md-6">
                                <input id="description" type="text"
                                    class="form-control{{ $errors->has('description')
                                ?
                                ' is-invalid' : '' }}" name="description"
                                value="{{
                                old('description') }}" required autofocus>

                                @if ($errors->has('description'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/rewards/rewards.blade.php
@extends('layouts.main')
@section('content')
<div class="row title">
    <h1>Poke rewards</h1>
</div>

<div class="row">
    @guest
    @else
    <div class="col-lg-1">
        @if(\Auth::user()->group == 42)
        <a href="{{ route('rewards.create') }}" class="btn btn-primary">
            Add
        </a>
        @endif
    </div>
    @endguest
</div>
<div class="sizedbox" style="padding: 10px;"></div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Status</th>
                <th scope="col">Active</th>
                <th scope="col">Created_at</th>
                <th scope="col">Updated_at</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach ( $rewards as $reward)
            <tr>
                <th scope="row">{{ $reward->id}}</th>
                <td>{{ $reward->title}}</td>
                <td>{{ $reward->description}}</td>
                <td>{{ $reward->status}}</td>
                <td>{{ $reward->active}}</td>
                <td>{{ $reward->created_at}}</td>
                <td>{{ $reward->updated_at}}</td>
                <td>
                    <form action="{{ route('rewards.destroy',[$reward->id])}}"
                        method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach

        </tbody>
    </table>


</div>
@stop