routes/web.php
<?php

use Illuminate\Support\Facades\Redirect;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
// Route::get('/home', function () {

// });
Route::get('/', 'StopController@index')->name('logged_out_home');
// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/home', 'StopController@index')->name('logged_in_home');
// Route::group(['middleware' => 'auth'], function () {
//     Route::post('stops', 'StopController@web_post')->name('stops_post');
// });
// stops
Route::resource(
    'stops',
    'StopController',
    ['only' => ['index', 'create', 'store', 'destroy', 'edit', 'update']]
);
Route::any('/stops/search', 'StopController@search')->name('stops.search');

Route::get('/stops/{id}/updatetask', 'StopController@update_task')->name('stops.updatetask');
Route::post('/stops/task/store', 'StopController@store_task')->name('stop.store.task');
//Route::get('posts/{post}/comments/{comment}', function ($postId, $commentId) {
//
//});
// Route::get('/stops', 'StopController@web_index')->name('stops');
// Route::get('/stops/create', 'StopController@web_create')->name('create_stop');
// Route::post('/stops/store', 'StopController@web_store')->name('store_stop');
// tasks
Route::resource(
    'tasks',
    'TaskController',
    ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]
);
// Route::get('/tasks', 'TaskController@web_index')->name('tasks.index');
// Route::get('/tasks/create', 'TaskController@web_create')->name('tasks.create');
// Route::post('/tasks/store', 'TaskController@web_store')->name('tasks.store');
// Route::delete('/tasks/destroy/{id}', 'TaskController@destroy')->name('tasks.destroy');
// rewards
Route::resource(
    'rewards',
    'RewardController',
    ['only' => ['index', 'create', 'store', 'destroy']]
);

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
    public function rewards()
    {
        return $this->belongsToMany(
            'App\Reward',
            'tasks_rewards',
            'tasks_id',
            'rewards_id'
        );
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Task;
use App\Reward;
use App\Http\Resources\Task as TaskResource;
use View;
use function GuzzleHttp\Promise\all;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function index()
    // {
    //     // Get tasks
    //     $tasks = Task::all();
    //     // Return collection of tasks as a resource
    //     return TaskResource::collection($tasks);
    // }
    public function index()
    {
        $tasks = Task::all();
        return View::make('tasks.tasks', compact('tasks'));
    }
    public function create()
    {
        if (\Auth::user()->group != 42) {
            return redirect('home');
        }
        $task = new Task();
        return View::make('tasks.create', compact('task'));
    }
    public function edit($id)
    {
        if (\Auth::user()->group != 42) {
            return redirect('home');
        }
        $rewards = Reward::all();
        $task = Task::with('rewards')->find($id);
        return View::make('tasks.edit', compact('task', 'rewards'));
    }
    public function update(Request $request, $id)
    {
        if (\Auth::user()->group != 42 && !Task::findOrFail($id)) {
            return redirect('home');
        }


        if ($request->input('rewards_id')) {
            $task = Task::findOrFail($id);
            $task->rewards()->attach($request->input('rewards_id'));
            return redirect()->route('tasks.edit', $id);
        } else
        if ($request->input('connected_rewards_id')) {
            $task = Task::findOrFail($id);
            $task->rewards()->detach($request->input('connected_rewards_id'));
            return redirect()->route('tasks.edit', $id);
        } else {
            $task = Task::findOrFail($id);
            $task->title = $request->input('title');
            $task->description = $request->input('description');
            if ($task->save()) {
                return redirect('tasks');
            }
        }
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    // public function store(Request $request)
    // {
    //     if (\Auth::user()->group != 42) {
    //         return redirect('home');
    //     }
    //     $task = $request->isMethod('put') ? Task::findOrFail($request->task_id) : new Task;
    //     $task->id = $request->input('task_id');
    //     $task->title = $request->input('title');
    //     $task->description = $request->input('description');
    //     $task->active = $request->input('active') ? $request->input('active') : 0;
    //     $task->status = $request->input('status') ? $request->input('status') : 'requested';
    //     if ($task->save()) {
    //         return new TaskResource($task);
    //     }
    // }
    public function store(Request $request)
    {
        if (\Auth::user()->group != 42) {
            return redirect('home');
        }
        $task = $request->isMethod('put') ? Task::findOrFail($request->task_id) : new Task;
        $task->id = $request->input('task_id');
        $task->title = $request->input('title');
        $task->description = $request->input('description');
        $task->active = $request->input('active') ? $request->input('active') : 0;
        $task->status = $request->input('status') ? $request->input('status') : 'requested';
        if ($task->save()) {
            return redirect('tasks');
        }
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function show($id)
    // {
    //     // Get task
    //     $task = Task::findOrFail($id);
    //     // Return single task as a resource
    //     return new TaskResource($task);
    // }

    public function destroy($id)
    {

        if (\Auth::user()->group != 42) {
            return redirect('home');
        }

        $task = Task::findOrFail($id);
        if ($task->delete()) {
            return redirect('tasks');
        }
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Task</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('tasks.store') }}"
                        aria-label="Create Task">
                        @csrf

                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label
                                text-md-right">Task title</label>

                            <div class="col-md-6">
                                <input id="title" type="text"
                                    class="form-control{{ $errors->has('title')
                                ?
                                ' is-invalid' : '' }}" name="title" value="{{
                                old('title') }}" required autofocus>

                                @if ($errors->has('title'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="description" class="col-md-4
                                col-form-label
                                text-md-right">Task description</label>

                            <div class="col-md-6">
                                <input id="description" type="text"
                                    class="form-control{{ $errors->has('description')
                                ?
                                ' is-invalid' : '' }}" name="description"
                                value="{{
                                old('description') }}" required autofocus>

                                @if ($errors->has('description'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/tasks/edit.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Update Task</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('tasks.update', $task->id)
                        }}"
                        aria-label="Update task">
                        @method('PATCH')
                        @csrf

                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label
                                text-md-right">Task title</label>

                            <div class="col-md-6">
                                <input id="title" type="text"
                                    class="form-control{{ $errors->has('title')
                                ?
                                ' is-invalid' : '' }}" name="title"
                                value="{{$task->title }}" required autofocus>
                                @if ($errors->has('title'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="description" class="col-md-4
                                col-form-label
                                text-md-right">Task description</label>

                            <div class="col-md-6">
                                <input id="description" type="text"
                                    class="form-control{{ $errors->has('description')
                                ?
                                ' is-invalid' : '' }}" name="description"
                                value="{{$task->description }}" required
                                autofocus>

                                @if ($errors->has('description'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>
    <br>
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="card">
                <div class="card-header">Add Reward</div>


                <div class="card-body">
                    <form method="POST" action="{{ route('tasks.update', $task->id)
                        }}"
                        aria-label="Update task">
                        @method('PATCH')
                        @csrf
                        <div class="form-group row">
                            <label for="rewards_id" class="col-md-4
                                col-form-label
                                text-md-right">Reward</label>
                            <div class="col-md-6">
                                <select class="form-control" id="reward"
                                    name="rewards_id">
                                    @foreach($rewards as $reward)
                                    <option value="{{$reward->id}}">{{$reward->title}}
                                        : {{$reward->description}}</option>
                                    @endforeach

                                </select>
                            </div>

                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Add
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

    @if($task->rewards->count()!=0)
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="card">
                <div class="card-header">Connected Reward</div>


                <div class="card-body">
                    <form method="POST" action="{{ route('tasks.update',
                        $task->id)
                        }}"
                        aria-label="Update task">
                        @method('PATCH')
                        @csrf
                        <div class="form-group row">
                            <label for="rewards_id" class="col-md-4
                                col-form-label
                                text-md-right">Rewards </label>
                            <div class="col-md-6">
                                <select class="form-control" id="reward"
                                    name="connected_rewards_id">
                                    @foreach($task->rewards as $reward)
                                    <option value="{{$reward->id}}">{{$reward->title}}
                                        : {{$reward->description}}</option>
                                    @endforeach

                                </select>
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn
                                    btn-danger">
                                    remove
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        @endif
    </div>
</div>
@stop

resources/views/tasks/tasks.blade.php
@extends('layouts.main')
@section('content')
<div class="row title">
    <h1>Poke tasks</h1>
</div>

<div class="row">
    @guest
    @else
    <div class="col-lg-1">
        @if(\Auth::user()->group == 42)
        <a href="{{ route('tasks.create') }}" class="btn btn-primary">
            Add
        </a>
        @endif
    </div>
    @endguest
</div>
<div class="sizedbox" style="padding: 10px;"></div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Status</th>
                <th scope="col">Active</th>
                <th scope="col">Created_at</th>
                <th scope="col">Updated_at</th>
                <th scope="col">Delete</th>
                <th scope="col">Edit</th>
            </tr>
        </thead>
        <tbody>
            @foreach ( $tasks as $task)
            <tr>
                <th scope="row">{{ $task->id}}</th>
                <td>{{ $task->title}}</td>
                <td>{{ $task->description}}</td>
                <td>{{ $task->status}}</td>
                <td>{{ $task->active}}</td>
                <td>{{ $task->created_at}}</td>
                <td>{{ $task->updated_at}}</td>
                <td>
                    <form action="{{ route('tasks.destroy',[$task->id])}}"
                        method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
                <td>
                    <a href="{{ route('tasks.edit',$task->id)}}" class="btn
                        btn-primary">Edit</a>
                </td>
            </tr>
            @endforeach

        </tbody>
    </table>


</div>
@stop